-- مهاجرت ۴: زیرمسئله‌های اختصاصی مترو و اتوبوس/بی‌آر‌تی + گزینه‌ی «خودم می‌نویسم» در هر دسته
-- اجرای دوباره‌ی این فایل بی‌خطر است.
BEGIN;

ALTER TABLE "subcategories" ADD COLUMN IF NOT EXISTS "modes" TEXT NOT NULL DEFAULT 'metro,bus,brt';
ALTER TABLE "subcategories" ADD COLUMN IF NOT EXISTS "isOther" BOOLEAN NOT NULL DEFAULT FALSE;

INSERT INTO "subcategories" ("id","categoryId","titleFa","allowsPhoto","isSensitive","sortOrder","isOther","modes") VALUES
  ('1-1', '1', 'قطار دیر رسید یا نیامد', FALSE, FALSE, 10, FALSE, 'metro'),
  ('1-6', '1', 'اتوبوس دیر رسید یا نیامد', FALSE, FALSE, 20, FALSE, 'bus,brt'),
  ('1-2', '1', 'فاصله بین قطارها زیاد است و باید خیلی منتظر بمانم', FALSE, FALSE, 30, FALSE, 'metro'),
  ('1-7', '1', 'باید خیلی در ایستگاه منتظر اتوبوس بمانم', FALSE, FALSE, 40, FALSE, 'bus,brt'),
  ('1-3', '1', 'قطار طبق زمانِ نمایش‌داده‌شده روی تابلو نرسید', FALSE, FALSE, 50, FALSE, 'metro'),
  ('1-8', '1', 'اتوبوس طبق زمانِ اعلام‌شده (تابلو یا اپلیکیشن) نرسید', FALSE, FALSE, 60, FALSE, 'bus,brt'),
  ('1-4', '1', 'به‌خاطر تأخیر به قطار بعدی در ایستگاه تبادلی نرسیدم', FALSE, FALSE, 70, FALSE, 'metro'),
  ('1-9', '1', 'به‌خاطر تأخیر به اتوبوس یا مترو بعدی نرسیدم', FALSE, FALSE, 80, FALSE, 'bus,brt'),
  ('1-5', '1', 'سرویس دیر شروع شد یا زود تمام شد', FALSE, FALSE, 90, FALSE, 'metro,bus,brt'),
  ('1-99', '1', 'مورد دیگری هست که در این فهرست نیست (خودم می‌نویسم)', TRUE, FALSE, 999, TRUE, 'metro,bus,brt'),
  ('2-1', '2', 'قطار وسط مسیر یا داخل تونل ایستاد', FALSE, FALSE, 10, FALSE, 'metro'),
  ('2-8', '2', 'اتوبوس وسط مسیر ایستاد یا خراب شد', FALSE, FALSE, 20, FALSE, 'bus,brt'),
  ('2-2', '2', 'داخل وسیله بیش از حد شلوغ بود', TRUE, FALSE, 30, FALSE, 'metro,bus,brt'),
  ('2-6', '2', 'روی سکو یا داخل ایستگاه بیش از حد شلوغ بود', TRUE, FALSE, 40, FALSE, 'metro,bus,brt'),
  ('2-3', '2', 'در ساعت شلوغی تعداد قطارها کم است', FALSE, FALSE, 50, FALSE, 'metro'),
  ('2-9', '2', 'در ساعت شلوغی تعداد اتوبوس‌ها کم است', FALSE, FALSE, 60, FALSE, 'bus,brt'),
  ('2-4', '2', 'قطار در ایستگاه نایستاد', FALSE, FALSE, 70, FALSE, 'metro'),
  ('2-10', '2', 'اتوبوس در ایستگاه نایستاد و رد شد', FALSE, FALSE, 80, FALSE, 'bus,brt'),
  ('2-5', '2', 'ایستگاه یا بخشی از خط بدون اطلاع قبلی بسته بود', FALSE, FALSE, 90, FALSE, 'metro'),
  ('2-11', '2', 'اتوبوس بدون اطلاع مسیرش را عوض کرد', FALSE, FALSE, 100, FALSE, 'bus,brt'),
  ('2-12', '2', 'درِ قطار گیر کرد، دیر باز شد یا زود بسته شد', FALSE, FALSE, 110, FALSE, 'metro'),
  ('2-13', '2', 'راننده درها را باز نکرد یا با درِ باز حرکت کرد', FALSE, FALSE, 120, FALSE, 'bus,brt'),
  ('2-14', '2', 'راننده خیلی تند یا خطرناک رانندگی می‌کرد', FALSE, FALSE, 130, FALSE, 'bus,brt'),
  ('2-15', '2', 'خودروهای دیگر وارد خط ویژه اتوبوس شده بودند', TRUE, FALSE, 140, FALSE, 'bus,brt'),
  ('2-7', '2', 'رفتار نامناسب کارکنان یا راننده', FALSE, FALSE, 150, FALSE, 'metro,bus,brt'),
  ('2-99', '2', 'مورد دیگری هست که در این فهرست نیست (خودم می‌نویسم)', TRUE, FALSE, 999, TRUE, 'metro,bus,brt'),
  ('3-1', '3', 'پله‌برقی خراب است', TRUE, FALSE, 10, FALSE, 'metro,bus,brt'),
  ('3-2', '3', 'آسانسور خراب است یا وجود ندارد', TRUE, FALSE, 20, FALSE, 'metro,bus,brt'),
  ('3-3', '3', 'هوای ایستگاه یا قطار خیلی گرم یا سرد است', FALSE, FALSE, 30, FALSE, 'metro'),
  ('3-12', '3', 'کولر یا بخاری اتوبوس یا ایستگاه کار نمی‌کند', FALSE, FALSE, 40, FALSE, 'bus,brt'),
  ('3-4', '3', 'روشنایی کم است', TRUE, FALSE, 50, FALSE, 'metro,bus,brt'),
  ('3-5', '3', 'نظافت رعایت نشده است', TRUE, FALSE, 60, FALSE, 'metro,bus,brt'),
  ('3-6', '3', 'درب، صندلی یا نرده‌ی ایستگاه یا قطار خراب است', TRUE, FALSE, 70, FALSE, 'metro'),
  ('3-13', '3', 'صندلی، دستگیره یا پنجره‌ی اتوبوس خراب است', TRUE, FALSE, 80, FALSE, 'bus,brt'),
  ('3-16', '3', 'سایبان، نیمکت یا درِ ایستگاه خراب یا آسیب‌دیده است', TRUE, FALSE, 90, FALSE, 'bus,brt'),
  ('3-17', '3', 'اتوبوس با سکو فاصله یا اختلاف ارتفاع دارد و سوار شدن سخت است', TRUE, FALSE, 100, FALSE, 'bus,brt'),
  ('3-14', '3', 'نشتی آب یا آسیب در سقف و دیوار ایستگاه', TRUE, FALSE, 110, FALSE, 'metro'),
  ('3-15', '3', 'پله یا کف ایستگاه لغزنده یا شکسته است (خطر افتادن)', TRUE, FALSE, 120, FALSE, 'metro'),
  ('3-18', '3', 'سرویس بهداشتی ایستگاه خراب یا بسته است', TRUE, FALSE, 130, FALSE, 'metro'),
  ('3-7', '3', 'مسیر برای ویلچر، سالمند یا نابینا مناسب نیست', TRUE, FALSE, 140, FALSE, 'metro,bus,brt'),
  ('3-8', '3', 'گیت ورودی یا دستگاه بلیت خراب است', TRUE, FALSE, 150, FALSE, 'metro'),
  ('3-9', '3', 'مسیر رفتن از مترو به اتوبوس (یا برعکس) مشکل دارد', TRUE, FALSE, 160, FALSE, 'metro,bus,brt'),
  ('3-10', '3', 'مسیر تبادل باریک یا خیلی شلوغ است', TRUE, FALSE, 170, FALSE, 'metro,bus,brt'),
  ('3-11', '3', 'بوی بد یا آلودگی محیط', TRUE, FALSE, 180, FALSE, 'metro,bus,brt'),
  ('3-99', '3', 'مورد دیگری هست که در این فهرست نیست (خودم می‌نویسم)', TRUE, FALSE, 999, TRUE, 'metro,bus,brt'),
  ('4-1', '4', 'مزاحمت کلامی', FALSE, TRUE, 10, FALSE, 'metro,bus,brt'),
  ('4-2', '4', 'مزاحمت یا آزار فیزیکی', FALSE, TRUE, 20, FALSE, 'metro,bus,brt'),
  ('4-9', '4', 'آزار جنسیتی', FALSE, TRUE, 30, FALSE, 'metro,bus,brt'),
  ('4-3', '4', 'جیب‌بری یا سرقت', FALSE, TRUE, 40, FALSE, 'metro,bus,brt'),
  ('4-4', '4', 'احساس ناامنی در محیط', FALSE, TRUE, 50, FALSE, 'metro,bus,brt'),
  ('4-5', '4', 'درگیری یا نزاع', FALSE, TRUE, 60, FALSE, 'metro,bus,brt'),
  ('4-10', '4', 'شرایط تهدیدکننده برای سالمند، کودک یا فرد آسیب‌پذیر', FALSE, TRUE, 70, FALSE, 'metro,bus,brt'),
  ('4-11', '4', 'ورود آقایان به واگن بانوان', FALSE, FALSE, 80, FALSE, 'metro'),
  ('4-12', '4', 'ورود آقایان به بخش بانوان', FALSE, FALSE, 90, FALSE, 'bus,brt'),
  ('4-13', '4', 'هل دادن و فشار خطرناک هنگام سوار و پیاده شدن', FALSE, FALSE, 100, FALSE, 'metro,bus,brt'),
  ('4-6', '4', 'حضور افراد در وضعیت بحران (مثلاً بیهوشی یا حال بد)', FALSE, FALSE, 110, FALSE, 'metro,bus,brt'),
  ('4-7', '4', 'دستفروشی مزاحم', TRUE, FALSE, 120, FALSE, 'metro,bus,brt'),
  ('4-8', '4', 'رفتار ناهنجار (سیگار، سروصدا)', FALSE, FALSE, 130, FALSE, 'metro,bus,brt'),
  ('4-99', '4', 'مورد دیگری هست که در این فهرست نیست (خودم می‌نویسم)', FALSE, TRUE, 999, TRUE, 'metro,bus,brt'),
  ('5-1', '5', 'درباره‌ی اختلال یا تأخیر هیچ اطلاعی ندادند', FALSE, FALSE, 10, FALSE, 'metro,bus,brt'),
  ('5-5', '5', 'علت تأخیر مبهم یا ناقص اعلام شد', FALSE, FALSE, 20, FALSE, 'metro,bus,brt'),
  ('5-6', '5', 'مسیر جایگزین را اعلام نکردند', FALSE, FALSE, 30, FALSE, 'metro,bus,brt'),
  ('5-7', '5', 'در محل تبادل مترو و اتوبوس راهنمایی نبود', TRUE, FALSE, 40, FALSE, 'metro,bus,brt'),
  ('5-2', '5', 'تابلوی زمان ورود قطار خراب یا خاموش است', TRUE, FALSE, 50, FALSE, 'metro'),
  ('5-8', '5', 'تابلوی اطلاعات ایستگاه خراب یا خاموش است', TRUE, FALSE, 60, FALSE, 'bus,brt'),
  ('5-3', '5', 'زمان ورود قطار روی تابلو نادرست بود', TRUE, FALSE, 70, FALSE, 'metro'),
  ('5-9', '5', 'زمان رسیدن اتوبوس روی تابلو یا اپلیکیشن نادرست بود', TRUE, FALSE, 80, FALSE, 'bus,brt'),
  ('5-10', '5', 'اعلام صوتی داخل قطار یا ایستگاه قطع یا نامفهوم بود', FALSE, FALSE, 90, FALSE, 'metro'),
  ('5-11', '5', 'ایستگاه بعدی داخل اتوبوس اعلام نمی‌شود', FALSE, FALSE, 100, FALSE, 'bus,brt'),
  ('5-12', '5', 'شماره یا مسیر خط روی اتوبوس یا ایستگاه مشخص نیست', TRUE, FALSE, 110, FALSE, 'bus,brt'),
  ('5-4', '5', 'تابلوی راهنما برای پیدا کردن مسیر یا خروجی نبود', TRUE, FALSE, 120, FALSE, 'metro,bus,brt'),
  ('5-99', '5', 'مورد دیگری هست که در این فهرست نیست (خودم می‌نویسم)', TRUE, FALSE, 999, TRUE, 'metro,bus,brt'),
  ('6-1', '6', 'کارت بلیت شارژ نشد', TRUE, FALSE, 10, FALSE, 'metro,bus,brt'),
  ('6-7', '6', 'شارژ از طریق اپلیکیشن یا پرداخت آنلاین مشکل داشت', FALSE, FALSE, 20, FALSE, 'metro,bus,brt'),
  ('6-2', '6', 'مبلغ اشتباه از کارتم کم شد', TRUE, FALSE, 30, FALSE, 'metro,bus,brt'),
  ('6-6', '6', 'مبلغ کرایه با مبلغ اعلام‌شده فرق داشت', FALSE, FALSE, 40, FALSE, 'metro,bus,brt'),
  ('6-3', '6', 'گیت یا دستگاه کارت‌خوان ایستگاه خراب است', TRUE, FALSE, 50, FALSE, 'metro'),
  ('6-5', '6', 'دستگاه کارت‌خوان اتوبوس یا ایستگاه خراب است', TRUE, FALSE, 60, FALSE, 'bus,brt'),
  ('6-4', '6', 'کارتم پذیرفته نشد', TRUE, FALSE, 70, FALSE, 'metro,bus,brt'),
  ('6-8', '6', 'راننده یا فروشنده بیشتر از کرایه پول گرفت', FALSE, FALSE, 80, FALSE, 'bus,brt'),
  ('6-99', '6', 'مورد دیگری هست که در این فهرست نیست (خودم می‌نویسم)', TRUE, FALSE, 999, TRUE, 'metro,bus,brt'),
  ('7-1', '7', 'سایر موارد', TRUE, FALSE, 10, TRUE, 'metro,bus,brt')
ON CONFLICT ("id") DO UPDATE SET
  "titleFa" = EXCLUDED."titleFa", "allowsPhoto" = EXCLUDED."allowsPhoto", "isSensitive" = EXCLUDED."isSensitive",
  "sortOrder" = EXCLUDED."sortOrder", "isOther" = EXCLUDED."isOther", "modes" = EXCLUDED."modes";

COMMIT;
