-- categories
INSERT INTO categories VALUES('1','مسائل زمانی 🕐',1,NULL);
INSERT INTO categories VALUES('2','مسائل عملیاتی ⚙️',2,NULL);
INSERT INTO categories VALUES('3','مسائل کالبدی و محیطی 🏗️',3,NULL);
INSERT INTO categories VALUES('4','مسائل اجتماعی و امنیتی 🛡️',4,NULL);
INSERT INTO categories VALUES('5','مسائل اطلاع‌رسانی 📢',5,NULL);
INSERT INTO categories VALUES('6','مسائل کرایه و پرداخت 💳',6,NULL);
INSERT INTO categories VALUES('7','سایر ✏️',7,NULL);

-- subcategories
INSERT INTO subcategories VALUES('1-1','1','تأخیر در رسیدن قطار/اتوبوس',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('1-2','1','فاصله زمانی طولانی بین سرویس‌ها',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('1-3','1','عدم تطابق با زمان‌بندی اعلام‌شده',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('1-4','1','از دست دادن اتصال در ایستگاه تبادلی',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('1-5','1','شروع دیرهنگام یا قطع زودهنگام سرویس',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('2-1','2','توقف یا اختلال در حرکت',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('2-2','2','ازدحام بیش از ظرفیت',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('2-3','2','کمبود ناوگان در ساعت اوج',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('2-4','2','عدم توقف در ایستگاه',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('2-5','2','تغییر مسیر بدون اطلاع‌رسانی',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-1','3','پله‌برقی خراب',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-2','3','آسانسور خراب یا موجود نبودن',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-3','3','تهویه نامناسب (گرما/سرما)',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-4','3','روشنایی ناکافی',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-5','3','نظافت نامناسب',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-6','3','خرابی درب، صندلی یا تجهیزات',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-7','3','مشکل دسترسی افراد دارای معلولیت',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('3-8','3','خرابی دستگاه بلیت یا گیت',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('4-1','4','مزاحمت کلامی',FALSE,TRUE,0,NULL);
INSERT INTO subcategories VALUES('4-2','4','مزاحمت یا آزار فیزیکی',FALSE,TRUE,0,NULL);
INSERT INTO subcategories VALUES('4-3','4','جیب‌بری یا سرقت',FALSE,TRUE,0,NULL);
INSERT INTO subcategories VALUES('4-4','4','احساس ناامنی در محیط',FALSE,TRUE,0,NULL);
INSERT INTO subcategories VALUES('4-5','4','درگیری یا نزاع',FALSE,TRUE,0,NULL);
INSERT INTO subcategories VALUES('4-6','4','حضور افراد در وضعیت بحران',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('4-7','4','دستفروشی مزاحم',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('4-8','4','رفتار ناهنجار (سیگار، سروصدا)',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('5-1','5','نبود اطلاع‌رسانی درباره اختلال',FALSE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('5-2','5','تابلوی اطلاعات خراب یا خاموش',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('5-3','5','اعلام زمان نادرست',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('5-4','5','نبود راهنمای مسیر یا تابلوی جهت‌یابی',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('6-1','6','مشکل در شارژ کارت بلیت',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('6-2','6','کسر اشتباه وجه',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('6-3','6','خرابی گیت یا دستگاه اعتبارسنجی',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('6-4','6','عدم پذیرش کارت',TRUE,FALSE,0,NULL);
INSERT INTO subcategories VALUES('7-1','7','سایر موارد',TRUE,FALSE,0,NULL);

-- lines
INSERT INTO lines VALUES('line-1','خط ۱ (تجریش - کهریزک)','metro','#E3000F');
INSERT INTO lines VALUES('line-2','خط ۲ (صادقیه - فرهنگسرا)','metro','#0039A6');
INSERT INTO lines VALUES('line-3','خط ۳ (قائم - آزادگان)','metro','#00BCE4');
INSERT INTO lines VALUES('line-4','خط ۴ (شهید کلاهدوز - ارم سبز)','metro','#FFD700');
INSERT INTO lines VALUES('line-5','خط ۵ (صادقیه - گلشهر)','metro','#008000');
INSERT INTO lines VALUES('line-6','خط ۶ (دولت‌آباد - کوهسار)','metro','#FF69B4');
INSERT INTO lines VALUES('line-7','خط ۷ (بسیج - میدان کتاب)','metro','#8A2BE2');
INSERT INTO lines VALUES('brt-1','خط ۱ BRT (چهارراه تهرانپارس - آزادی)','brt','#FF0000');
INSERT INTO lines VALUES('brt-7','خط ۷ BRT (راه‌آهن - تجریش)','brt','#00FF00');

-- stations
INSERT INTO stations VALUES('st-bulk-1','تجریش','["line-1"]',35.8055000000000021,51.42840000000000344,FALSE);
INSERT INTO stations VALUES('st-bulk-2','قیطریه','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-3','شهید صدر','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-4','قلهک','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-5','دکتر شریعتی','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-6','میرداماد','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-7','شهید حقانی','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-8','شهید همت','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-9','مصلی امام خمینی','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-10','شهید بهشتی','["line-1", "line-3"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-11','شهید مفتح','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-12','شهدای هفتم تیر','["line-1", "line-6"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-13','طالقانی','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-14','دروازه دولت','["line-1", "line-4"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-15','سعدی','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-16','امام خمینی','["line-1", "line-2"]',35.68650000000000233,51.42079999999999985,TRUE);
INSERT INTO stations VALUES('st-bulk-17','پانزده خرداد','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-18','خیام','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-19','میدان محمدیه','["line-1", "line-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-20','شوش','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-21','پایانه جنوب','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-22','شهید بخارایی','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-23','علی‌آباد','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-24','جوانمرد قصاب','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-25','شهرری','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-26','پالایشگاه','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-27','شاهد - باقرشهر','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-28','حرم امام خمینی','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-29','کهریزک','["line-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-30','صادقیه','["line-2", "line-5"]',35.71970000000000312,51.3464000000000027,TRUE);
INSERT INTO stations VALUES('st-bulk-31','طرشت','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-32','دانشگاه شریف','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-33','شادمان','["line-2", "line-4"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-34','شهید نواب صفوی','["line-2", "line-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-35','میدان حر','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-36','دانشگاه امام علی','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-37','حسن‌آباد','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-38','ملت','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-39','بهارستان','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-40','دروازه شمیران','["line-2", "line-4"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-41','امام حسین','["line-2", "line-6"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-42','شهید مدنی','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-43','سبلان','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-44','فدک','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-45','جانبازان','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-46','سرسبز','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-47','دانشگاه علم و صنعت','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-48','شهید باقری','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-49','تهرانپارس','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-50','فرهنگسرا','["line-2"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-51','قائم','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-52','شهید محلاتی','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-53','نوبنیاد','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-54','حسین‌آباد','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-55','میدان هروی','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-56','شهید زین‌الدین','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-57','خواجه عبدالله انصاری','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-58','شهید صیاد شیرازی','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-59','شهید قدوسی','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-60','سهروردی','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-61','میرزای شیرازی','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-62','میدان جهاد','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-63','میدان ولیعصر','["line-3", "line-6"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-64','تئاتر شهر','["line-3", "line-4"]',35.70089999999999719,51.40200000000000102,TRUE);
INSERT INTO stations VALUES('st-bulk-65','منیریه','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-66','راه‌آهن','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-67','جوادیه','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-68','زمزم','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-69','شهرک شریعتی','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-70','عبدالآباد','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-71','نعمت‌آباد','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-72','آزادگان','["line-3"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-73','شهید کلاهدوز','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-74','نیروی هوایی','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-75','نبرد','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-76','پیروزی','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-77','ابن‌سینا','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-78','میدان شهدا','["line-4", "line-6"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-79','فردوسی','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-80','میدان انقلاب اسلامی','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-81','توحید','["line-4", "line-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-82','دکتر حبیب‌الله','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-83','استاد معین','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-84','میدان آزادی','["line-4", "brt-1"]',35.69969999999999999,51.34790000000000276,TRUE);
INSERT INTO stations VALUES('st-bulk-85','بیمه','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-86','شهرک اکباتان','["line-4"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-87','ارم سبز','["line-4", "line-5"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-88','چهارراه تهرانپارس','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-89','داریوش','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-90','آیت','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-91','ابوریحان','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-92','خاقانی','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-93','وحیدیه','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-94','سبلان','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-95','فرودگاه','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-96','منتظری','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-97','میدان امام حسین (ع)','["brt-1"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-98','پل چوبی','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-99','پیچ شمیران','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-100','دروازه دولت','["brt-1"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-101','میدان فردوسی','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-102','چهارراه ولیعصر (تئاتر شهر)','["brt-1", "brt-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-103','دانشگاه تهران','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-104','میدان انقلاب اسلامی','["brt-1"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-105','قریب','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-106','نواب','["brt-1"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-107','بهبودی','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-108','دانشگاه شریف','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-109','استاد معین','["brt-1"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-111','میدان تجریش','["brt-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-112','باغ فردوس','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-113','محمودیه','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-114','چهارراه پارک وی','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-115','امانیه','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-116','نیایش','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-117','ظفر','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-118','میرداماد','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-119','میدان ونک','["brt-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-120','همت','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-121','توانیر','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-122','پله سوم','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-123','شهید بهشتی','["brt-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-124','شهید مطهری','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-125','میدان ولیعصر (عج)','["brt-7"]',NULL,NULL,TRUE);
INSERT INTO stations VALUES('st-bulk-126','طالقانی','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-127','جمهوری','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-128','جامی','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-129','منیریه','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-130','میدان قزوین','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-131','مولوی','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-132','مختاری','["brt-7"]',NULL,NULL,FALSE);
INSERT INTO stations VALUES('st-bulk-133','میدان راه‌آهن','["brt-7"]',NULL,NULL,TRUE);
